### ISSUE TITLE
[FEAT] Desenvolver os Controllers\Routers da API

### ISSUE THREAD

**Issue by Frotas** [Squad-61/recreio_backend#6]
# Criar os Controllers\Routers da API

## O que é um Controller?
 
Um **Controller é responsável tanto por receber requisições como por enviar a resposta ao usuário**, algo bem parecido com o Servlet do JSP. Porém, é feito de forma mais elegante e fácil. O **Controller se responsabiliza por informar a View, os atributos que serão visíveis para a mesma e também por receber parâmetros vindos da View**. E, por último, responder ao usuário o que foi requisitado.

![Diagrama de Classe](https://user-images.githubusercontent.com/89676387/193425698-6b4bb93e-45eb-4521-8279-dee1ccd4dbc1.jpg)

No diagrama de classe no pacote **CONTROLLER** podemos ver que há oito classes, elas serão responsaveis por solicitar, salvar, alterar, deletar e tratra os dados que vem da **VIEW**.

## Task

- [ ] Student Controller:
    - Responsavel por criar, salvar, atualizar e deletar um aluno da plataforma
    - [x] Implementação do metodo de **salvamento do perfil de um aluno**
    - [x] Implementação do metodo de **atualização do perfil de um aluno existente**
    - [ ] implementação do metodo de: (**OPERAÇÃO SOMENTE REALIZADA PELO RESPONSAVEL**)
      - [ ] **arquivamento**
      - [ ] **exclusão**

- [ ] Parent Controller:
    - Responsavel por criar, salvar, atualizar e deletar o responsavel de um aluno da plataforma
    - [x] Implementação do metodo de **salvamento do perfil de um responavel**
    - [x] Implementação do metodo de **atualização do perfil de um resposavel existente**
    - [ ] implementação do metodo de:
      - [ ] **arquivamento**
      - [ ] **exclusão**

- [ ] Teacher Controller:
    - Responsavel por criar, salvar, atualizar e deletar um professor da plataforma
    - [x] Implementação do metodo de **salvamento do perfil do professor**
    - [x] Implementação do metodo de **atualização de um perfil de professor existente**
    - [ ] implementação do metodo de:
      - [ ] **arquivamento**
      - [ ] **exclusão**

- [ ] Contract Controller:
    - Responsavel por criar, salvar, atualizar e deletar um contrato com um professor cadastrado na plataforma.
    - [x] Implementação do metodo de **salvamento do contrato e vinculo com um professor existente**
    - [x] Implementação do metodo de **atualização de um contrato existente**
    - [ ] implementação do metodo de 
      - [ ] **arquivamento** 
      - [ ] **exclusão**
- [ ] ...

Além das funções supracitadas, tende-se de ajustar as entidades mapeadas para tais operação, sendo assim, refazer o relacionamento das mesmas.

- [ ] Atualização do Diagrama de Entidade de Relacionamento
  - [x] Ajustes no relacionamento entre as entidades
  - [x] Ajustes dos campos das entidades
  - [ ] Normalização das entidades com JPA
- [ ] Atualizar os _models_
   - [ ] Remapeamento da entidade _Student_
  - [ ] Remapeamento da entidade _Parent_
  - [ ] Remapeamento da entidade _Teacher_

**Comment by Frotas** [comment]
Além das funções supracitadas, tende-se de ajustar as entidades mapeadas para tais operação, sendo assim, refazer o relacionamento das mesmas.

- [ ] Atualização do Diagrama de Entidade de Relacionamento
  - [ ] Ajustes no relacionamento entre as entidades
  - [ ] Ajustes dos campos das entidades
  - [ ] Normalização das entidades com JPA
- [ ] Atualizar os _models_
   - [ ] Remapeamento da entidade _Student_
  - [ ] Remapeamento da entidade _Parent_
  - [ ] Remapeamento da entidade _Teacher_
